version: "3.3"

services:
  nodejs:
    build:
      context: .
    image: node:latest
    ports:
      - 4000:4000
    volumes:
      - .:/data/app:delegated
      - ./package.json:/data/package.json
      - ./package-lock.json:/data/package.lock.json

  database:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=graphql
      - MYSQL_USER=usuario
      - MYSQL_PASSWORD=123
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --character-set-filesystem=utf8
    ports:
      - 3306:3306
    volumes:
      - './volumes/database/data:/var/lib/mysql'

      